server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.qexzpkwrfjlblrvtqvuh
    password: hubble@56183
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: huychienthan999@gmail.com
    password: fkhifplujjzuqkub
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: MzM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=
  access-token-expiration: 3600000
  refresh-token-expiration: 2592000000

aws:
  s3:
    bucket-name: hubble-media
    region: ap-southeast-1
    access-key: YOUR_AWS_ACCESS_KEY
    secret-key: YOUR_AWS_SECRET_KEY

google:
  client-id: 571998074420-sc599ois6r8jm4c1sg09q4d9d6nbpbv6.apps.googleusercontent.com

otp:
  expiry-minutes: 5
  length: 6

logging:
  level:
    com.hubble: DEBUG

app:
  storage:
    provider: minio
    endpoint: http://localhost:9000
    access-key: minioadmin
    secret-key: minioadmin
    bucket: hubble-media
    public-url: http://10.0.2.2:9000/hubble-media
    max-file-size-mb: 25
    allowed-types:
      - image/jpeg
      - image/png
      - image/gif
      - image/webp
      - video/mp4
      - audio/mpeg
      - audio/mp4
      - audio/ogg
      - audio/aac
      - audio/m4a
      - audio/x-m4a
      - audio/mpeg
      - application/pdf
      - application/octet-stream